/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frms;

import java.io.File;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JOptionPane;

/**
 *
 * @author marcos-adm
 */
public class EletroCalc extends javax.swing.JFrame {    
    /**
     * Creates new form EletroCalc
     */
    Integer ind;
    String  ref;
    Float V, R, U, I, P;
    
    public EletroCalc() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpRotulo = new javax.swing.JPanel();
        jtV1 = new javax.swing.JTextField();
        jtV2 = new javax.swing.JTextField();
        jlResultado = new javax.swing.JLabel();
        jlV1 = new javax.swing.JLabel();
        jlV2 = new javax.swing.JLabel();
        jcbEscolha = new javax.swing.JComboBox();
        jbCalculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlFormula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eletro - Calc");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpRotulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpRotulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtV1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpRotulo.add(jtV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 20));

        jtV2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpRotulo.add(jtV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, 20));

        jlResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRotulo.add(jlResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, 20));

        jlV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlV1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRotulo.add(jlV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 20));

        jlV2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlV2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRotulo.add(jlV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 20));

        jcbEscolha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha", "Corrente", "Tensão", "Potência", "Resistência" }));
        jcbEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEscolhaActionPerformed(evt);
            }
        });
        jpRotulo.add(jcbEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));

        jbCalculo.setText("Calcular");
        jbCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalculoActionPerformed(evt);
            }
        });
        jpRotulo.add(jbCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 30));

        jLabel1.setText("Fórmula:");
        jpRotulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jlFormula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFormula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpRotulo.add(jlFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Resultado");
        jpRotulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, -1));

        jPanel1.add(jpRotulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalculoActionPerformed
        // TODO add your handling code here:
        try {
            switch (ind){
                case 0 :
                 V = Float.parseFloat(jtV1.getText());
                 R = Float.parseFloat(jtV2.getText());
                 I = V/R;
                 jlResultado.setText(Float.toString(I));
                    break;
                    
                case 1 :
                    R = Float.parseFloat(jtV1.getText());
                    I = Float.parseFloat(jtV2.getText());
                    V = R*I;
                    jlResultado.setText(Float.toString(V));
                 
                    break;
                    
                case 2 :
                    U = Float.parseFloat(jtV1.getText());
                    R = Float.parseFloat(jtV2.getText());
                    P = U*R;
                    jlResultado.setText(Float.toString(P));
                                     
                    break;
                    
                case 3 :    
                    V = Float.parseFloat(jtV1.getText());
                    I = Float.parseFloat(jtV2.getText());
                    R = V/I;
                    jlResultado.setText(Float.toString(R));
                                     
                    break;
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog (null, e);
            
        }
    }//GEN-LAST:event_jbCalculoActionPerformed

    private void jcbEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEscolhaActionPerformed
        // TODO add your handling code here:
        try {
            ref= jcbEscolha.getSelectedItem().toString();
            
            if (ref=="Corrente"){
                jlV1.setText("Valor de V");
                jlV2.setText("Valor de R");
                jlFormula.setText("i=V/R");
                ind = 0;
                
            }
            
            if (ref=="Tensão"){
                jlV1.setText("Valor de R");
                jlV2.setText("Valor de i");
                jlFormula.setText("V=R.i");
                ind = 1;
            }
            //P=U.i P=R.i² P=U²/R
            if (ref=="Potência"){
                jlV1.setText("Valor de U");
                jlV2.setText("Valor de i");
                jlFormula.setText("P=U.i");
                ind = 2;
            }
            
            if (ref=="Resistência"){
                jlV1.setText("Valor de V");
                jlV2.setText("Valor de i");
                jlFormula.setText("R=V/i");
                ind = 3;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog (null, e);
        }
    }//GEN-LAST:event_jcbEscolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EletroCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EletroCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EletroCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EletroCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EletroCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCalculo;
    private javax.swing.JComboBox jcbEscolha;
    private javax.swing.JLabel jlFormula;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JLabel jlV1;
    private javax.swing.JLabel jlV2;
    private javax.swing.JPanel jpRotulo;
    private javax.swing.JTextField jtV1;
    private javax.swing.JTextField jtV2;
    // End of variables declaration//GEN-END:variables
}
